### ISSUE TITLE
No infracost cloud with bitbucket/jenkins

### ISSUE THREAD

**Issue by korenlev** [infracost/infracost-jenkins#14]
To reproduce:
1.bitbucket (cloud).
2. Jenkins (server)
3. Follow infracost guides.

PR comments added to bitbucket
infracost comment phase - does not update infracost cloud with PR details (while all 5 ENV vars set per the guide.

**Comment by alikhajeh1** [comment]
Hi @korenlev - thanks for creating this issue, I've replied to you over email as I need to check your Infracost Cloud account to debug further.
